GET https://puhelinluettelo-adlh.onrender.com/api/persons 
Accept: application/json

###

GET https://puhelinluettelo-adlh.onrender.com/info
Accept: text/html

###

DELETE https://puhelinluettelo-adlh.onrender.com/api/persons/:1